workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'

image: node:20-alpine

variables:
  NODE_ENV: development

stages:
  - install
  - build
  - image

cache:
  paths:
    - node_modules/
  key: "$CI_COMMIT_REF_SLUG"

# Installer les d√©pendances
install-frontend-job:
  stage: install
  script:
    - npm ci

# Build de l'application
build-frontend-job:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    name: "frontend-dist-artifacts"

# Build et push de l'image Docker
image-frontend-job:
  stage: image
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build-frontend-job
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t divineion/abernathyclinic-client:$CI_COMMIT_REF_SLUG .
    - docker push divineion/abernathyclinic-client:$CI_COMMIT_REF_SLUG